name: Build and deploy Python app to Azure Web App - reverse-image-search-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - uses: actions/checkout@v4

      # Step 2: Set up Python version
      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Zip the app for deployment
      - name: Zip artifact for deployment
        run: zip -r app.zip ./* -x "*.git*" "venv/*"

      # Step 5: Upload artifact
      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Step 1: Download artifact from build job
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      # Step 2: Unzip artifact
      - name: Unzip artifact
        run: unzip app.zip

      # Step 3: Login to Azure using Publish Profile
      - name: Login to Azure
        uses: azure/login@v2
        with:
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

      # Step 4: Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'reverse-image-search-api'
